<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PolyHook2.NET" Version="1.1.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MioModdingApi">
      <HintPath>../MioModdingApi/bin/Debug/net8.0/MioModdingApi.dll</HintPath>
    </Reference>
    <Reference Include="MioModLoader">
      <HintPath>../lib/MioModLoader.dll</HintPath>
    </Reference>
    <Reference Include="MioBinds">
      <HintPath>../lib/MioBinds.dll</HintPath>
    </Reference>
  </ItemGroup>
	
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call &quot;$(ProjectDir)post-build.bat&quot; &quot;$(TargetPath)&quot; &quot;$(ProjectName)&quot;" />
	</Target>

</Project>
